### ISSUE TITLE
Any idea how to disable outbound email?

### ISSUE THREAD

**Issue by Wardrop** [nijel/rt2zammad#1]
Hi,

In the README it's suggested to disable outbound mail from Zammad. Have you got any suggestion on how best to achieve this? It doesn't look like Zammad allows us to disable outbound mail, and it's too clever to accept a bogus smtp server.

Cheers

**Comment by nijel** [comment]
You can disable sending all notifications types in Zammad. I'm using my own SMTP with Zammad and I've configured it to discard any mail just to be sure, but I don't think it was necessary.
